name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}} 
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build the Docker image
        run: docker build -t ${{secrets.DOCKERHUB_REPO}} .

      - name: Tag the Docker image
        run: docker tag ${{secrets.DOCKERHUB_REPO}}:latest ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB_REPO}}:latest

      - name: Push the Docker image to DockerHub
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB_REPO}}:latest
        
      - name: Set execute permission on deploy.sh
        run: chmod +x /path/to/deploy.sh
        
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }} # pem 키
          script: |
            sudo docker rm -f $(docker ps -aqf "name=^${{secrets.DOCKERHUB_REPO}}") # 컨테이너 찾아서 종료
            sudo docker pull ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB_REPO}}:latest
            sudo docker run -d -p 80:80 --name ${{secrets.DOCKERHUB_REPO}} ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB_REPO}}:latest
            sudo docker image prune -f
            
      - name: Zip create
        run: zip -qq -r ./build-fe.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./build-fe.zip s3://yukgaejang-bucket/build-fe.zip
      
      - name: 이전 배포 삭제
        run: aws deploy stop-deployment --deployment-id d-1CUWABY26 --region ${{secrets.AWS_REGION}} || echo "No active deployment to stop"

      - name: Deploy to CodeDeploy
        run: aws deploy create-deployment --application-name Yukgaejang-inflearn-clone --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name Yukgaejang --s3-location bucket=yukgaejang-bucket,key=build-fe.zip,bundleType=zip
